### ISSUE TITLE
Order of width and height

### ISSUE THREAD

**Issue by ZoeBijl** [jonathantneal/postcss-short-size#1]
Most css properties follow the vertical followed by horizontal pattern, like padding, margin, and border-width. Should this follow that logic? Also see this proposal: http://discourse.wicg.io/t/shorthand-for-width-height-css-longhands/1160

**Comment by jonathantneal** [comment]
Thanks for the ideas! I believe these concerns are addressed in [v1.1.0](https://github.com/jonathantneal/postcss-short-size/commit/0560f91bd36f50681eb1ab672eb0a5d2f1c48ea5), also based upon [this conversation](https://twitter.com/tabatkins/status/706172377676124161) and [responses](https://discourse.wicg.io/t/shorthand-for-width-height-css-longhands/1160/15) to the proposal you shared.
